version: "3"
services:
  node-app:
    build: .
    ports:
      - "3000:4000"
    volumes:
      - ./:/app:ro
      - /app/node_modules
    # enviroment:
    #   - PORT=3000
    env_file:
      - ./.env